import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ru' | 'uz' | 'en' | 'kz' | 'kg';

export const languageNames: Record<Language, string> = {
  ru: 'Русский',
  uz: "O'zbek",
  en: 'English',
  kz: 'Қазақша',
  kg: 'Кыргызча',
};

export const languageFlags: Record<Language, string> = {
  ru: '🇷🇺',
  uz: '🇺🇿',
  en: '🇬🇧',
  kz: '🇰🇿',
  kg: '🇰🇬',
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ru';
  });
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const detectCountryLanguage = async () => {
      // If user already has a saved preference, don't override
      if (localStorage.getItem('language')) {
        setIsInitialized(true);
        return;
      }

      try {
        const response = await fetch('https://ipapi.co/json/');
        const data = await response.json();
        
        // If user is in Uzbekistan, set Uzbek as default
        if (data.country_code === 'UZ') {
          setLanguageState('uz');
          localStorage.setItem('language', 'uz');
        } else {
          // For all other countries, default to Russian
          setLanguageState('ru');
          localStorage.setItem('language', 'ru');
        }
      } catch (error) {
        // On error, default to Russian
        console.log('Could not detect country, defaulting to Russian');
        localStorage.setItem('language', 'ru');
      }
      
      setIsInitialized(true);
    };

    detectCountryLanguage();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // Keep <html lang="..."> in sync with current language
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        // Fallback to Russian
        value = translations.ru;
        for (const k2 of keys) {
          if (value && typeof value === 'object' && k2 in value) {
            value = value[k2];
          } else {
            return key;
          }
        }
        break;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, any> = {
  ru: {
    nav: {
      home: 'Главная',
      search: 'Найти врача',
      clinics: 'Клиники',
      promotions: 'Акции',
      articles: 'Статьи',
      about: 'О проекте',
      login: 'Войти',
      profile: 'Профиль',
      logout: 'Выйти',
    },
    hero: {
      badge: '#1 Платформа стоматологов в Центральной Азии',
      subtitle: 'Премиум Портал Стоматологов Центральной Азии',
      description: '500+ проверенных врачей, мгновенная запись онлайн, реальные отзывы и фото работ',
      selectSpecialty: 'Выберите специальность',
      selectCity: 'Выберите город',
      searchButton: 'Найти',
      doctors: 'Врачей',
      rating: 'Рейтинг',
      appointments: 'Записей',
      quickLinks: {
        implants: 'Имплантация',
        braces: 'Брекеты',
        whitening: 'Отбеливание',
        veneers: 'Виниры',
        caries: 'Лечение кариеса',
      },
      specialties: {
        therapist: 'Терапевт',
        orthodontist: 'Ортодонт',
        surgeon: 'Хирург',
        orthopedist: 'Ортопед',
        periodontist: 'Пародонтолог',
        pediatric: 'Детский стоматолог',
      },
      cities: {
        tashkent: 'Ташкент',
        samarkand: 'Самарканд',
        bukhara: 'Бухара',
        andijan: 'Андижан',
        namangan: 'Наманган',
      },
    },
    features: {
      badge: 'ПОЧЕМУ МЫ',
      title: 'Преимущества',
      brandName: 'PRODENT',
      subtitle: 'Мы делаем поиск стоматолога простым, быстрым и надежным',
      booking: {
        title: 'Запись за 7 секунд',
        description: 'Быстрая онлайн-запись без звонков и ожидания',
      },
      verified: {
        title: 'Проверенные врачи',
        description: 'Все специалисты с подтвержденными сертификатами',
      },
      reviews: {
        title: 'Реальные отзывы',
        description: 'Только отзывы от реальных пациентов с проверкой',
      },
      video: {
        title: 'Видео работ',
        description: 'Смотрите результаты «до» и «после» в формате видео',
      },
      reminders: {
        title: 'Напоминания',
        description: 'SMS и Push-уведомления о предстоящем визите',
      },
      premium: {
        title: 'Только премиум',
        description: 'Лучшие клиники и специалисты Центральной Азии',
      },
    },
    doctors: {
      badge: 'ТОП СПЕЦИАЛИСТЫ',
      title: 'Лучшие врачи',
      viewAll: 'Все врачи',
      experience: 'лет опыта',
      from: 'от',
      book: 'Записаться',
      viewProfile: 'Профиль',
      verified: 'Проверен',
      sum: 'сум',
    },
    promotions: {
      title: 'Актуальные',
      titleHighlight: 'акции',
      subtitle: 'Специальные предложения от лучших клиник Ташкента',
      book: 'Записаться',
      viewAll: 'Смотреть все акции',
      validUntil: 'До',
      noPromotions: 'Нет акций в выбранной категории',
      categories: {
        all: 'Все',
        hygiene: 'Гигиена',
        orthodontics: 'Ортодонтия',
        aesthetics: 'Эстетика',
        implants: 'Имплантация',
        treatment: 'Лечение',
        pediatric: 'Детская',
        surgery: 'Хирургия',
        periodontics: 'Пародонтология',
        prosthetics: 'Протезирование',
      },
    },
    clinics: {
      title: 'Стоматологические клиники',
      subtitle: 'Найдите лучшую клинику рядом с вами',
      searchPlaceholder: 'Поиск по названию клиники...',
      filters: 'Фильтры',
      searchFilters: 'Фильтры поиска',
      activeFilters: 'Активные фильтры:',
      search: 'Поиск',
      city: 'Город',
      allCities: 'Все города',
      district: 'Район',
      allDistricts: 'Все районы',
      verifiedOnly: 'Только проверенные',
      resetFilters: 'Сбросить фильтры',
      resetAll: 'Сбросить все',
      verified: 'Проверено',
      doctors: 'врачей',
      clinicFound: 'клиника найдена',
      clinicsFound2to4: 'клиники найдено',
      clinicsFound5plus: 'клиник найдено',
      notFound: 'Клиники не найдены',
      notFoundHint: 'Попробуйте изменить параметры поиска',
      website: 'Сайт',
      email: 'Почта',
      onMap: 'На карте',
    },
    clinicProfile: {
      doctors: 'Врачи',
      about: 'О клинике',
    },
    footer: {
      description: 'Первый премиум-портал стоматологов в Центральной Азии',
      patients: 'Пациентам',
      findDoctor: 'Найти врача',
      clinics: 'Клиники',
      promotions: 'Акции',
      reviews: 'Отзывы',
      services: 'Услуги',
      implants: 'Имплантация',
      braces: 'Брекеты',
      whitening: 'Отбеливание',
      veneers: 'Виниры',
      contacts: 'Контакты',
      address: 'Ташкент, ул. Амира Темура, 129',
      rights: 'Все права защищены',
      privacy: 'Политика конфиденциальности',
      terms: 'Условия использования',
    },
    search: {
      title: 'Поиск врача',
      placeholder: 'Поиск по имени врача или клинике...',
      onMap: 'На карте',
      filters: 'Фильтры',
      specialty: 'Специальность',
      allSpecialties: 'Все специальности',
      city: 'Город',
      district: 'Район',
      allDistricts: 'Все районы',
      price: 'Цена',
      rating: 'Рейтинг',
      andAbove: 'и выше',
      withVideo: 'Только с видео работ',
      resetFilters: 'Сбросить фильтры',
      found: 'Найдено',
      doctorsCount: 'врачей',
      sort: 'Сортировка',
      byRating: 'По рейтингу',
      byPriceAsc: 'По цене (возр.)',
      byPriceDesc: 'По цене (убыв.)',
      byExperience: 'По опыту',
      verified: 'Проверен',
      years: 'лет',
      book: 'Записаться',
      notFound: 'Врачи не найдены',
      downloadApp: 'Скачайте приложение',
      appDescription: 'Управляйте записями и получайте напоминания',
      downloadIn: 'Загрузить в',
      availableIn: 'Доступно в',
      sum: 'сум',
    },
    articles: {
      title: 'Полезные статьи',
      subtitle: 'Экспертные материалы о здоровье зубов',
      heroTitle: 'Полезные статьи о стоматологии',
      heroSubtitle: 'Экспертные материалы о здоровье зубов от ведущих специалистов',
      readMore: 'Читать далее',
      featured: 'Рекомендуемое',
      readTime: 'мин чтения',
      backToArticles: 'К статьям',
      relatedArticles: 'Похожие статьи',
      noArticles: 'Статьи не найдены',
      categories: {
        all: 'Все статьи',
        prevention: 'Профилактика',
        treatment: 'Лечение',
        children: 'Детская стоматология',
        cosmetic: 'Косметическая стоматология',
      },
    },
    auth: {
      login: 'Вход',
      register: 'Регистрация',
      loginTab: 'Вход',
      registerTab: 'Регистрация',
      email: 'Email',
      password: 'Пароль',
      confirmPassword: 'Подтвердите пароль',
      fullName: 'Полное имя',
      phone: 'Телефон',
      forgotPassword: 'Забыли пароль?',
      noAccount: 'Нет аккаунта?',
      hasAccount: 'Уже есть аккаунт?',
      accountType: 'Тип аккаунта',
      patient: 'Пациент',
      doctor: 'Врач',
      clinic: 'Клиника',
      loginButton: 'Войти',
      registerButton: 'Зарегистрироваться',
      or: 'Или',
      googleLogin: 'Войти через Google',
      termsText: 'Продолжая, вы соглашаетесь с нашими',
      termsLink: 'условиями использования',
      and: 'и',
      privacyLink: 'политикой конфиденциальности',
      createAccount: 'Создайте аккаунт для доступа к платформе',
      loginToAccount: 'Войдите в свой аккаунт',
      doctorNote: 'После регистрации вам нужно будет заполнить заявку с документами для проверки администратором',
      passwordMismatch: 'Пароли не совпадают',
      passwordTooShort: 'Пароль должен содержать минимум 6 символов',
    },
    profile: {
      tabs: {
        timeline: 'Лента',
        portfolio: 'Портфолио',
        reviews: 'Отзывы',
        about: 'О враче',
        services: 'Услуги',
        settings: 'Настройки',
      },
      follow: 'Подписаться',
      following: 'Подписан',
      message: 'Написать',
      book: 'Записаться',
      followers: 'подписчиков',
      experience: 'лет опыта',
      patients: 'пациентов',
      reviews: 'отзывов',
      verified: 'Проверен',
      edit: 'Редактировать',
      save: 'Сохранить',
      cancel: 'Отмена',
    },
    crm: {
      dashboard: 'Дашборд',
      patients: 'Пациенты',
      appointments: 'Записи',
      schedule: 'Расписание',
      finance: 'Финансы',
      inventory: 'Склад',
      laboratory: 'Лаборатория',
      reports: 'Отчеты',
      settings: 'Настройки',
      notifications: 'Уведомления',
      queue: 'Очередь',
      medicalRecords: 'Мед. карты',
      ads: 'Реклама',
      profile: 'Профиль',
      doctorRequests: 'Запросы врачей',
      messages: 'Сообщения',
      services: 'Услуги',
      billing: 'Оплата и подписки',
      lightTheme: 'Светлая тема',
      darkTheme: 'Тёмная тема',
      logout: 'Выход',
    },
    patient: {
      dashboard: 'Главная',
      appointments: 'Записи',
      medical: 'Мед. карта',
      payments: 'Платежи',
      doctors: 'Мои врачи',
      messages: 'Сообщения',
      files: 'Файлы',
      family: 'Семья',
      reminders: 'Напоминания',
      history: 'История',
      bookAppointment: 'Записаться',
    },
    common: {
      loading: 'Загрузка...',
      error: 'Ошибка',
      success: 'Успешно',
      save: 'Сохранить',
      cancel: 'Отмена',
      delete: 'Удалить',
      edit: 'Редактировать',
      add: 'Добавить',
      close: 'Закрыть',
      confirm: 'Подтвердить',
      back: 'Назад',
      next: 'Далее',
      submit: 'Отправить',
      search: 'Поиск',
      all: 'Все',
      yes: 'Да',
      no: 'Нет',
      or: 'или',
      from: 'от',
      to: 'до',
      today: 'Сегодня',
      yesterday: 'Вчера',
      tomorrow: 'Завтра',
      week: 'Неделя',
      month: 'Месяц',
      year: 'Год',
    },
    landing: {
      heroTitle: 'Премиум Портал',
      heroHighlight: 'Стоматологов Центральной Азии',
      heroSubtitle: 'Найдите своего стоматолога',
      heroDescription: '500+ проверенных врачей в одном месте. Онлайн-запись, реальные отзывы и фото работ.',
      findDoctor: 'Найти врача',
      viewClinics: 'Смотреть клиники',
      statDoctors: 'Врачей',
      statRating: 'Рейтинг',
      statAppointments: 'Записей',
      crmBadge: 'Для клиник и врачей',
      crmTitle: 'Всё в одном месте',
      crmSubtitle: 'Полноценная CRM-система для управления клиникой, профилем врача и работой с пациентами',
      doctorProfile: 'Профиль врача',
      doctorProfileDesc: 'Создайте профессиональный профиль с портфолио работ, сертификатами и отзывами пациентов. Привлекайте новых клиентов через онлайн-записи.',
      clinicManagement: 'Управление клиникой',
      clinicManagementDesc: 'Единая платформа для всех процессов: от записи до финансов и аналитики. Контролируйте все аспекты работы клиники.',
      patientDatabase: 'База пациентов',
      patientDatabaseDesc: 'Полная история лечения, зубная карта и планы лечения в одном месте. Мгновенный доступ ко всей информации о пациенте.',
      connectClinic: 'Подключить клинику',
      howItWorks: 'Как это работает',
      howItWorksSubtitle: 'Всего 3 простых шага до идеальной улыбки',
      step1Title: 'Найдите врача',
      step1Desc: 'Используйте удобные фильтры для поиска идеального специалиста. Выберите специальность, город, рейтинг и ценовой диапазон.',
      step2Title: 'Изучите профиль',
      step2Desc: 'Посмотрите полный профиль врача с фотографиями работ, реальными отзывами пациентов и сертификатами.',
      step3Title: 'Запишитесь онлайн',
      step3Desc: 'Выберите удобное время и запишитесь к врачу в пару кликов. Получите мгновенное подтверждение записи.',
      ctaTitle: 'Готовы найти своего врача?',
      ctaSubtitle: 'Присоединяйтесь к тысячам пациентов, которые уже нашли своего стоматолога',
      startSearch: 'Начать поиск',
      login: 'Войти',
      interfaceTitle: 'Интерфейс системы',
      interfaceSubtitle: 'Современный и интуитивно понятный интерфейс для эффективной работы',
    },
  },
  uz: {
    nav: {
      home: 'Bosh sahifa',
      search: 'Shifokor topish',
      clinics: 'Klinikalar',
      promotions: 'Aksiyalar',
      articles: 'Maqolalar',
      about: 'Loyiha haqida',
      login: 'Kirish',
      profile: 'Profil',
      logout: 'Chiqish',
    },
    hero: {
      badge: "Markaziy Osiyoning №1 Stomatologiya Platformasi",
      subtitle: "Markaziy Osiyoning Premium Stomatologiya Portali",
      description: "500+ tasdiqlangan shifokorlar, onlayn tez yozilish, haqiqiy sharhlar va ish fotolari",
      selectSpecialty: 'Mutaxassislikni tanlang',
      selectCity: 'Shaharni tanlang',
      searchButton: 'Topish',
      doctors: 'Shifokorlar',
      rating: 'Reyting',
      appointments: 'Yozuvlar',
      quickLinks: {
        implants: 'Implantatsiya',
        braces: 'Breketlar',
        whitening: 'Oqartirish',
        veneers: 'Vinirlar',
        caries: 'Kariesni davolash',
      },
      specialties: {
        therapist: 'Terapevt',
        orthodontist: 'Ortodont',
        surgeon: 'Jarroh',
        orthopedist: 'Ortoped',
        periodontist: 'Parodontolog',
        pediatric: 'Bolalar stomatolgi',
      },
      cities: {
        tashkent: 'Toshkent',
        samarkand: 'Samarqand',
        bukhara: 'Buxoro',
        andijan: 'Andijon',
        namangan: 'Namangan',
      },
    },
    features: {
      badge: 'NEGA BIZ',
      title: 'Afzalliklar',
      brandName: 'PRODENT',
      subtitle: "Biz stomatolog qidirishni oson, tez va ishonchli qilamiz",
      booking: {
        title: "7 soniyada yozilish",
        description: "Qo'ng'iroqsiz va kutmasdan tez onlayn yozilish",
      },
      verified: {
        title: 'Tasdiqlangan shifokorlar',
        description: "Tasdiqlangan sertifikatlarga ega barcha mutaxassislar",
      },
      reviews: {
        title: 'Haqiqiy sharhlar',
        description: "Faqat tekshirilgan haqiqiy bemorlardan sharhlar",
      },
      video: {
        title: "Ishlar videolari",
        description: "Video formatida \"oldin\" va \"keyin\" natijalarni ko'ring",
      },
      reminders: {
        title: 'Eslatmalar',
        description: "Kelayotgan tashrif haqida SMS va Push-bildirishnomalar",
      },
      premium: {
        title: "Faqat premium",
        description: "Markaziy Osiyoning eng yaxshi klinikalari va mutaxassislari",
      },
    },
    doctors: {
      badge: 'TOP MUTAXASSISLAR',
      title: 'Eng yaxshi shifokorlar',
      viewAll: 'Barcha shifokorlar',
      experience: 'yil tajriba',
      from: 'dan',
      book: 'Yozilish',
      viewProfile: 'Profil',
      verified: 'Tasdiqlangan',
      sum: "so'm",
    },
    promotions: {
      title: 'Dolzarb',
      titleHighlight: 'aksiyalar',
      subtitle: "Toshkentning eng yaxshi klinikalaridan maxsus takliflar",
      book: 'Yozilish',
      viewAll: "Barcha aksiyalarni ko'rish",
      validUntil: 'Gacha',
      noPromotions: "Tanlangan kategoriyada aksiya yo'q",
      categories: {
        all: 'Hammasi',
        hygiene: 'Gigiena',
        orthodontics: 'Ortodontiya',
        aesthetics: 'Estetika',
        implants: 'Implantatsiya',
        treatment: 'Davolash',
        pediatric: 'Bolalar',
        surgery: 'Jarrohlik',
        periodontics: 'Parodontologiya',
        prosthetics: 'Protezlash',
      },
    },
    clinics: {
      title: 'Stomatologiya klinikalari',
      subtitle: 'Yaqiningizdagi eng yaxshi klinikani toping',
      searchPlaceholder: 'Klinika nomi bo\'yicha qidirish...',
      filters: 'Filtrlar',
      searchFilters: 'Qidiruv filtrlari',
      activeFilters: 'Faol filtrlar:',
      search: 'Qidirish',
      city: 'Shahar',
      allCities: 'Barcha shaharlar',
      district: 'Tuman',
      allDistricts: 'Barcha tumanlar',
      verifiedOnly: 'Faqat tasdiqlangan',
      resetFilters: 'Filtrlarni tozalash',
      resetAll: 'Hammasini tozalash',
      verified: 'Tasdiqlangan',
      doctors: 'shifokor',
      clinicFound: 'klinika topildi',
      clinicsFound2to4: 'klinika topildi',
      clinicsFound5plus: 'klinika topildi',
      notFound: 'Klinikalar topilmadi',
      notFoundHint: 'Qidiruv parametrlarini o\'zgartirib ko\'ring',
      website: 'Sayt',
      email: 'Pochta',
      onMap: 'Xaritada',
    },
    clinicProfile: {
      doctors: 'Shifokorlar',
      about: 'Klinika haqida',
    },
    footer: {
      description: "Markaziy Osiyoning birinchi premium stomatologiya portali",
      patients: 'Bemorlarga',
      findDoctor: 'Shifokor topish',
      clinics: 'Klinikalar',
      promotions: 'Aksiyalar',
      reviews: 'Sharhlar',
      services: 'Xizmatlar',
      implants: 'Implantatsiya',
      braces: 'Breketlar',
      whitening: 'Oqartirish',
      veneers: 'Vinirlar',
      contacts: 'Kontaktlar',
      address: "Toshkent, Amir Temur ko'chasi, 129",
      rights: 'Barcha huquqlar himoyalangan',
      privacy: 'Maxfiylik siyosati',
      terms: "Foydalanish shartlari",
    },
    search: {
      title: 'Shifokor qidirish',
      placeholder: "Shifokor yoki klinika bo'yicha qidirish...",
      onMap: 'Xaritada',
      filters: 'Filtrlar',
      specialty: 'Mutaxassislik',
      allSpecialties: 'Barcha mutaxassisliklar',
      city: 'Shahar',
      district: 'Tuman',
      allDistricts: 'Barcha tumanlar',
      price: 'Narx',
      rating: 'Reyting',
      andAbove: 'va yuqori',
      withVideo: 'Faqat video ishlari bilan',
      resetFilters: 'Filtrlarni tozalash',
      found: 'Topildi',
      doctorsCount: 'shifokor',
      sort: 'Saralash',
      byRating: "Reyting bo'yicha",
      byPriceAsc: "Narx bo'yicha (oshish)",
      byPriceDesc: "Narx bo'yicha (kamayish)",
      byExperience: "Tajriba bo'yicha",
      verified: 'Tasdiqlangan',
      years: 'yil',
      book: 'Yozilish',
      notFound: 'Shifokorlar topilmadi',
      downloadApp: 'Ilovani yuklab oling',
      appDescription: "Yozuvlarni boshqaring va eslatmalar oling",
      downloadIn: 'Yuklab olish',
      availableIn: 'Mavjud',
      sum: "so'm",
    },
    articles: {
      title: 'Foydali maqolalar',
      subtitle: "Tish salomatligi haqida ekspert materiallari",
      heroTitle: 'Stomatologiya haqida foydali maqolalar',
      heroSubtitle: "Yetakchi mutaxassislardan tish salomatligi haqida ekspert materiallari",
      readMore: "Batafsil o'qish",
      featured: 'Tavsiya etilgan',
      readTime: "daqiqa o'qish",
      backToArticles: 'Maqolalarga',
      relatedArticles: "O'xshash maqolalar",
      noArticles: 'Maqolalar topilmadi',
      categories: {
        all: 'Barcha maqolalar',
        prevention: 'Profilaktika',
        treatment: 'Davolash',
        children: 'Bolalar stomatologiyasi',
        cosmetic: 'Kosmetik stomatologiya',
      },
    },
    auth: {
      login: 'Kirish',
      register: "Ro'yxatdan o'tish",
      loginTab: 'Kirish',
      registerTab: "Ro'yxatdan o'tish",
      email: 'Email',
      password: 'Parol',
      confirmPassword: 'Parolni tasdiqlang',
      fullName: "To'liq ism",
      phone: 'Telefon',
      forgotPassword: 'Parolni unutdingizmi?',
      noAccount: "Hisobingiz yo'qmi?",
      hasAccount: 'Hisobingiz bormi?',
      accountType: 'Hisob turi',
      patient: 'Bemor',
      doctor: 'Shifokor',
      clinic: 'Klinika',
      loginButton: 'Kirish',
      registerButton: "Ro'yxatdan o'tish",
      or: 'Yoki',
      googleLogin: 'Google orqali kirish',
      termsText: "Davom etish orqali siz bizning",
      termsLink: "foydalanish shartlarimizga",
      and: 'va',
      privacyLink: "maxfiylik siyosatimizga rozilik bildirasiz",
      createAccount: "Platformaga kirish uchun hisob yarating",
      loginToAccount: "Hisobingizga kiring",
      doctorNote: "Ro'yxatdan o'tgandan so'ng, administrator tekshiruvi uchun hujjatlar bilan ariza to'ldirishingiz kerak",
      passwordMismatch: 'Parollar mos kelmaydi',
      passwordTooShort: 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak',
    },
    profile: {
      tabs: {
        timeline: 'Lenta',
        portfolio: 'Portfolio',
        reviews: 'Sharhlar',
        about: 'Shifokor haqida',
        services: 'Xizmatlar',
        settings: 'Sozlamalar',
      },
      follow: 'Obuna',
      following: "Obuna bo'lgan",
      message: 'Yozish',
      book: 'Yozilish',
      followers: 'obunachi',
      experience: 'yil tajriba',
      patients: 'bemor',
      reviews: 'sharh',
      verified: 'Tasdiqlangan',
      edit: 'Tahrirlash',
      save: 'Saqlash',
      cancel: 'Bekor qilish',
    },
    crm: {
      dashboard: 'Boshqaruv paneli',
      patients: 'Bemorlar',
      appointments: 'Yozuvlar',
      schedule: 'Jadval',
      finance: 'Moliya',
      inventory: 'Ombor',
      laboratory: 'Laboratoriya',
      reports: 'Hisobotlar',
      settings: 'Sozlamalar',
      notifications: 'Bildirishnomalar',
      queue: 'Navbat',
      medicalRecords: 'Tibbiy kartalar',
      ads: 'Reklama',
      profile: 'Profil',
      doctorRequests: 'Shifokor so\'rovlari',
      messages: 'Xabarlar',
      services: 'Xizmatlar',
      billing: "To'lov va obunalar",
      lightTheme: 'Yorug mavzu',
      darkTheme: 'Qorong\'i mavzu',
      logout: 'Chiqish',
    },
    patient: {
      dashboard: 'Bosh sahifa',
      appointments: 'Yozuvlar',
      medical: 'Tibbiy karta',
      payments: "To'lovlar",
      doctors: 'Shifokorlarim',
      messages: 'Xabarlar',
      files: 'Fayllar',
      family: 'Oila',
      reminders: 'Eslatmalar',
      history: 'Tarix',
      bookAppointment: 'Yozilish',
    },
    common: {
      loading: 'Yuklanmoqda...',
      error: 'Xatolik',
      success: 'Muvaffaqiyatli',
      save: 'Saqlash',
      cancel: 'Bekor qilish',
      delete: "O'chirish",
      edit: 'Tahrirlash',
      add: "Qo'shish",
      close: 'Yopish',
      confirm: 'Tasdiqlash',
      back: 'Orqaga',
      next: 'Keyingi',
      submit: 'Yuborish',
      search: 'Qidirish',
      all: 'Hammasi',
      yes: 'Ha',
      no: "Yo'q",
      or: 'yoki',
      from: 'dan',
      to: 'gacha',
      today: 'Bugun',
      yesterday: 'Kecha',
      tomorrow: 'Ertaga',
      week: 'Hafta',
      month: 'Oy',
      year: 'Yil',
    },
    landing: {
      heroTitle: 'Premium Portal',
      heroHighlight: "Markaziy Osiyo Stomatologiyasi",
      heroSubtitle: "O'z stomatologingizni toping",
      heroDescription: "500+ tasdiqlangan shifokorlar bir joyda. Onlayn yozilish, haqiqiy sharhlar va ish suratlari.",
      findDoctor: 'Shifokor topish',
      viewClinics: 'Klinikalarni ko\'rish',
      statDoctors: 'Shifokorlar',
      statRating: 'Reyting',
      statAppointments: 'Yozilishlar',
      crmBadge: 'Klinikalar va shifokorlar uchun',
      crmTitle: 'Hammasi bir joyda',
      crmSubtitle: "Klinikani boshqarish, shifokor profili va bemorlar bilan ishlash uchun to'liq CRM-tizim",
      doctorProfile: 'Shifokor profili',
      doctorProfileDesc: "Portfolio, sertifikatlar va bemor sharhlari bilan professional profil yarating. Onlayn yozilish orqali yangi mijozlarni jalb qiling.",
      clinicManagement: 'Klinikani boshqarish',
      clinicManagementDesc: "Yozilishdan moliyagacha barcha jarayonlar uchun yagona platforma. Klinikaning barcha jihatlarini nazorat qiling.",
      patientDatabase: 'Bemorlar bazasi',
      patientDatabaseDesc: "To'liq davolash tarixi, tish kartasi va davolash rejalari bir joyda. Bemor haqidagi barcha ma'lumotlarga tezkor kirish.",
      connectClinic: "Klinikani ulash",
      howItWorks: 'Qanday ishlaydi',
      howItWorksSubtitle: "Mukammal tabassumgacha 3 oddiy qadam",
      step1Title: 'Shifokor toping',
      step1Desc: "Ideal mutaxassisni topish uchun qulay filtrlardan foydalaning. Mutaxassislik, shahar, reyting va narx oralig'ini tanlang.",
      step2Title: "Profilni o'rganing",
      step2Desc: "Shifokorning to'liq profilini ish suratlari, haqiqiy bemor sharhlari va sertifikatlar bilan ko'ring.",
      step3Title: 'Onlayn yozilin',
      step3Desc: "Qulay vaqtni tanlang va bir necha marta bosib shifokorga yozilin. Darhol tasdiqlash oling.",
      ctaTitle: "Shifokoringizni topishga tayyormisiz?",
      ctaSubtitle: "O'z stomatologini topgan minglab bemorlarga qo'shiling",
      startSearch: "Qidiruvni boshlash",
      login: 'Kirish',
      interfaceTitle: 'Tizim interfeysi',
      interfaceSubtitle: "Samarali ishlash uchun zamonaviy va qulay interfeys",
    },
  },
  en: {
    nav: {
      home: 'Home',
      search: 'Find Doctor',
      clinics: 'Clinics',
      promotions: 'Promotions',
      articles: 'Articles',
      about: 'About',
      login: 'Login',
      profile: 'Profile',
      logout: 'Logout',
    },
    hero: {
      badge: '#1 Dental Platform of Central Asia',
      subtitle: 'Premium Dental Portal of Central Asia',
      description: '500+ verified doctors, instant online booking, real reviews and work photos',
      selectSpecialty: 'Select specialty',
      selectCity: 'Select city',
      searchButton: 'Search',
      doctors: 'Doctors',
      rating: 'Rating',
      appointments: 'Bookings',
      quickLinks: {
        implants: 'Implants',
        braces: 'Braces',
        whitening: 'Whitening',
        veneers: 'Veneers',
        caries: 'Caries treatment',
      },
      specialties: {
        therapist: 'Therapist',
        orthodontist: 'Orthodontist',
        surgeon: 'Surgeon',
        orthopedist: 'Orthopedist',
        periodontist: 'Periodontist',
        pediatric: 'Pediatric dentist',
      },
      cities: {
        tashkent: 'Tashkent',
        samarkand: 'Samarkand',
        bukhara: 'Bukhara',
        andijan: 'Andijan',
        namangan: 'Namangan',
      },
    },
    features: {
      badge: 'WHY US',
      title: 'Advantages of',
      brandName: 'PRODENT',
      subtitle: 'We make finding a dentist simple, fast and reliable',
      booking: {
        title: 'Book in 7 seconds',
        description: 'Fast online booking without calls and waiting',
      },
      verified: {
        title: 'Verified doctors',
        description: 'All specialists with confirmed certificates',
      },
      reviews: {
        title: 'Real reviews',
        description: 'Only verified reviews from real patients',
      },
      video: {
        title: 'Work videos',
        description: 'Watch before and after results in video format',
      },
      reminders: {
        title: 'Reminders',
        description: 'SMS and Push notifications about upcoming visits',
      },
      premium: {
        title: 'Premium only',
        description: 'Best clinics and specialists of Central Asia',
      },
    },
    doctors: {
      badge: 'TOP SPECIALISTS',
      title: 'Best doctors',
      viewAll: 'All doctors',
      experience: 'years experience',
      from: 'from',
      book: 'Book',
      viewProfile: 'Profile',
      verified: 'Verified',
      sum: 'sum',
    },
    promotions: {
      title: 'Current',
      titleHighlight: 'promotions',
      subtitle: 'Special offers from the best clinics in Tashkent',
      book: 'Book',
      viewAll: 'View all promotions',
      validUntil: 'Until',
      noPromotions: 'No promotions in selected category',
      categories: {
        all: 'All',
        hygiene: 'Hygiene',
        orthodontics: 'Orthodontics',
        aesthetics: 'Aesthetics',
        implants: 'Implants',
        treatment: 'Treatment',
        pediatric: 'Pediatric',
        surgery: 'Surgery',
        periodontics: 'Periodontics',
        prosthetics: 'Prosthetics',
      },
    },
    clinics: {
      title: 'Dental Clinics',
      subtitle: 'Find the best clinic near you',
      searchPlaceholder: 'Search by clinic name...',
      filters: 'Filters',
      searchFilters: 'Search filters',
      activeFilters: 'Active filters:',
      search: 'Search',
      city: 'City',
      allCities: 'All cities',
      district: 'District',
      allDistricts: 'All districts',
      verifiedOnly: 'Verified only',
      resetFilters: 'Reset filters',
      resetAll: 'Reset all',
      verified: 'Verified',
      doctors: 'doctors',
      clinicFound: 'clinic found',
      clinicsFound2to4: 'clinics found',
      clinicsFound5plus: 'clinics found',
      notFound: 'No clinics found',
      notFoundHint: 'Try changing search parameters',
      website: 'Website',
      email: 'Email',
      onMap: 'On Map',
    },
    clinicProfile: {
      doctors: 'Doctors',
      about: 'About Clinic',
    },
    footer: {
      description: 'The first premium dental portal of Central Asia',
      patients: 'For Patients',
      findDoctor: 'Find Doctor',
      clinics: 'Clinics',
      promotions: 'Promotions',
      reviews: 'Reviews',
      services: 'Services',
      implants: 'Implants',
      braces: 'Braces',
      whitening: 'Whitening',
      veneers: 'Veneers',
      contacts: 'Contacts',
      address: 'Tashkent, Amir Temur str., 129',
      rights: 'All rights reserved',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
    },
    search: {
      title: 'Find a Doctor',
      placeholder: 'Search by doctor name or clinic...',
      onMap: 'On Map',
      filters: 'Filters',
      specialty: 'Specialty',
      allSpecialties: 'All specialties',
      city: 'City',
      district: 'District',
      allDistricts: 'All districts',
      price: 'Price',
      rating: 'Rating',
      andAbove: 'and above',
      withVideo: 'With work videos only',
      resetFilters: 'Reset filters',
      found: 'Found',
      doctorsCount: 'doctors',
      sort: 'Sort',
      byRating: 'By rating',
      byPriceAsc: 'By price (asc)',
      byPriceDesc: 'By price (desc)',
      byExperience: 'By experience',
      verified: 'Verified',
      years: 'years',
      book: 'Book',
      notFound: 'No doctors found',
      downloadApp: 'Download the app',
      appDescription: 'Manage appointments and get reminders',
      downloadIn: 'Download on',
      availableIn: 'Get it on',
      sum: 'sum',
    },
    articles: {
      title: 'Useful articles',
      subtitle: 'Expert materials on dental health',
      heroTitle: 'Useful articles about dentistry',
      heroSubtitle: 'Expert materials on dental health from leading specialists',
      readMore: 'Read more',
      featured: 'Featured',
      readTime: 'min read',
      backToArticles: 'Back to Articles',
      relatedArticles: 'Related articles',
      noArticles: 'No articles found',
      categories: {
        all: 'All articles',
        prevention: 'Prevention',
        treatment: 'Treatment',
        children: 'Pediatric dentistry',
        cosmetic: 'Cosmetic dentistry',
      },
    },
    auth: {
      login: 'Login',
      register: 'Register',
      loginTab: 'Login',
      registerTab: 'Register',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm password',
      fullName: 'Full name',
      phone: 'Phone',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      accountType: 'Account type',
      patient: 'Patient',
      doctor: 'Doctor',
      clinic: 'Clinic',
      loginButton: 'Login',
      registerButton: 'Register',
      or: 'Or',
      googleLogin: 'Login with Google',
      termsText: 'By continuing, you agree to our',
      termsLink: 'terms of use',
      and: 'and',
      privacyLink: 'privacy policy',
      createAccount: 'Create an account to access the platform',
      loginToAccount: 'Login to your account',
      doctorNote: 'After registration, you will need to fill out an application with documents for administrator verification',
      passwordMismatch: 'Passwords do not match',
      passwordTooShort: 'Password must be at least 6 characters',
    },
    profile: {
      tabs: {
        timeline: 'Timeline',
        portfolio: 'Portfolio',
        reviews: 'Reviews',
        about: 'About',
        services: 'Services',
        settings: 'Settings',
      },
      follow: 'Follow',
      following: 'Following',
      message: 'Message',
      book: 'Book',
      followers: 'followers',
      experience: 'years exp.',
      patients: 'patients',
      reviews: 'reviews',
      verified: 'Verified',
      edit: 'Edit',
      save: 'Save',
      cancel: 'Cancel',
    },
    crm: {
      dashboard: 'Dashboard',
      patients: 'Patients',
      appointments: 'Appointments',
      schedule: 'Schedule',
      finance: 'Finance',
      inventory: 'Inventory',
      laboratory: 'Laboratory',
      reports: 'Reports',
      settings: 'Settings',
      notifications: 'Notifications',
      queue: 'Queue',
      medicalRecords: 'Medical Records',
      ads: 'Advertising',
      profile: 'Profile',
      doctorRequests: 'Doctor Requests',
      messages: 'Messages',
      services: 'Services',
      billing: 'Billing & Subscriptions',
      lightTheme: 'Light theme',
      darkTheme: 'Dark theme',
      logout: 'Logout',
    },
    patient: {
      dashboard: 'Dashboard',
      appointments: 'Appointments',
      medical: 'Medical Card',
      payments: 'Payments',
      doctors: 'My Doctors',
      messages: 'Messages',
      files: 'Files',
      family: 'Family',
      reminders: 'Reminders',
      history: 'History',
      bookAppointment: 'Book Appointment',
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      close: 'Close',
      confirm: 'Confirm',
      back: 'Back',
      next: 'Next',
      submit: 'Submit',
      search: 'Search',
      all: 'All',
      yes: 'Yes',
      no: 'No',
      or: 'or',
      from: 'from',
      to: 'to',
      today: 'Today',
      yesterday: 'Yesterday',
      tomorrow: 'Tomorrow',
      week: 'Week',
      month: 'Month',
      year: 'Year',
    },
  },
  kz: {
    nav: {
      home: 'Басты бет',
      search: 'Дәрігер табу',
      clinics: 'Клиникалар',
      promotions: 'Акциялар',
      articles: 'Мақалалар',
      about: 'Жоба туралы',
      login: 'Кіру',
      profile: 'Профиль',
      logout: 'Шығу',
    },
    hero: {
      badge: 'Орталық Азияның №1 Стоматология Платформасы',
      subtitle: 'Орталық Азияның Премиум Стоматология Порталы',
      description: '500+ тексерілген дәрігерлер, онлайн тез жазылу, нақты пікірлер мен жұмыс фотолары',
      selectSpecialty: 'Мамандықты таңдаңыз',
      selectCity: 'Қаланы таңдаңыз',
      searchButton: 'Іздеу',
      doctors: 'Дәрігерлер',
      rating: 'Рейтинг',
      appointments: 'Жазылулар',
      quickLinks: {
        implants: 'Имплантация',
        braces: 'Брекеттер',
        whitening: 'Ағарту',
        veneers: 'Винирлер',
        caries: 'Кариесті емдеу',
      },
      specialties: {
        therapist: 'Терапевт',
        orthodontist: 'Ортодонт',
        surgeon: 'Хирург',
        orthopedist: 'Ортопед',
        periodontist: 'Пародонтолог',
        pediatric: 'Балалар стоматологі',
      },
      cities: {
        tashkent: 'Ташкент',
        samarkand: 'Самарқанд',
        bukhara: 'Бұхара',
        andijan: 'Андижан',
        namangan: 'Наманган',
      },
    },
    features: {
      badge: 'НЕГЕ БІЗ',
      title: 'Артықшылықтар',
      brandName: 'PRODENT',
      subtitle: 'Біз стоматолог іздеуді қарапайым, жылдам және сенімді етеміз',
      booking: {
        title: '7 секундта жазылу',
        description: 'Қоңыраусыз және күтусіз жылдам онлайн жазылу',
      },
      verified: {
        title: 'Тексерілген дәрігерлер',
        description: 'Расталған сертификаттары бар барлық мамандар',
      },
      reviews: {
        title: 'Нақты пікірлер',
        description: 'Тек тексерілген нақты пациенттерден пікірлер',
      },
      video: {
        title: 'Жұмыс бейнелері',
        description: '"Алдында" және "кейін" нәтижелерін бейне форматында көріңіз',
      },
      reminders: {
        title: 'Еске салулар',
        description: 'Алдағы сапар туралы SMS және Push-хабарламалар',
      },
      premium: {
        title: 'Тек премиум',
        description: 'Орталық Азияның үздік клиникалары мен мамандары',
      },
    },
    doctors: {
      badge: 'ТОП МАМАНДАР',
      title: 'Үздік дәрігерлер',
      viewAll: 'Барлық дәрігерлер',
      experience: 'жыл тәжірибе',
      from: 'бастап',
      book: 'Жазылу',
      viewProfile: 'Профиль',
      verified: 'Тексерілген',
      sum: 'сум',
    },
    promotions: {
      title: 'Өзекті',
      titleHighlight: 'акциялар',
      subtitle: 'Ташкенттің үздік клиникаларынан арнайы ұсыныстар',
      book: 'Жазылу',
      viewAll: 'Барлық акцияларды көру',
      validUntil: 'Дейін',
      noPromotions: 'Таңдалған санатта акция жоқ',
      categories: {
        all: 'Барлығы',
        hygiene: 'Гигиена',
        orthodontics: 'Ортодонтия',
        aesthetics: 'Эстетика',
        implants: 'Имплантация',
        treatment: 'Емдеу',
        pediatric: 'Балалар',
        surgery: 'Хирургия',
        periodontics: 'Пародонтология',
        prosthetics: 'Протездеу',
      },
    },
    clinics: {
      title: 'Стоматологиялық клиникалар',
      subtitle: 'Жақын маңдағы ең жақсы клиниканы табыңыз',
      searchPlaceholder: 'Клиника атауы бойынша іздеу...',
      filters: 'Сүзгілер',
      searchFilters: 'Іздеу сүзгілері',
      activeFilters: 'Белсенді сүзгілер:',
      search: 'Іздеу',
      city: 'Қала',
      allCities: 'Барлық қалалар',
      district: 'Аудан',
      allDistricts: 'Барлық аудандар',
      verifiedOnly: 'Тек тексерілгендер',
      resetFilters: 'Сүзгілерді тазалау',
      resetAll: 'Барлығын тазалау',
      verified: 'Тексерілген',
      doctors: 'дәрігер',
      clinicFound: 'клиника табылды',
      clinicsFound2to4: 'клиника табылды',
      clinicsFound5plus: 'клиника табылды',
      notFound: 'Клиникалар табылмады',
      notFoundHint: 'Іздеу параметрлерін өзгертіп көріңіз',
      website: 'Сайт',
      email: 'Пошта',
    },
    clinicProfile: {
      doctors: 'Дәрігерлер',
      about: 'Клиника туралы',
    },
    footer: {
      description: 'Орталық Азияның бірінші премиум стоматология порталы',
      patients: 'Пациенттерге',
      findDoctor: 'Дәрігер табу',
      clinics: 'Клиникалар',
      promotions: 'Акциялар',
      reviews: 'Пікірлер',
      services: 'Қызметтер',
      implants: 'Имплантация',
      braces: 'Брекеттер',
      whitening: 'Ағарту',
      veneers: 'Винирлер',
      contacts: 'Байланыс',
      address: 'Ташкент, Әмір Темір көш., 129',
      rights: 'Барлық құқықтар қорғалған',
      privacy: 'Құпиялылық саясаты',
      terms: 'Қолдану шарттары',
    },
    search: {
      title: 'Дәрігер іздеу',
      placeholder: 'Дәрігер немесе клиника бойынша іздеу...',
      onMap: 'Картада',
      filters: 'Сүзгілер',
      specialty: 'Мамандық',
      allSpecialties: 'Барлық мамандықтар',
      city: 'Қала',
      district: 'Аудан',
      allDistricts: 'Барлық аудандар',
      price: 'Баға',
      rating: 'Рейтинг',
      andAbove: 'және жоғары',
      withVideo: 'Тек жұмыс бейнелерімен',
      resetFilters: 'Сүзгілерді тазалау',
      found: 'Табылды',
      doctorsCount: 'дәрігер',
      sort: 'Сұрыптау',
      byRating: 'Рейтинг бойынша',
      byPriceAsc: 'Баға бойынша (өсу)',
      byPriceDesc: 'Баға бойынша (кему)',
      byExperience: 'Тәжірибе бойынша',
      verified: 'Тексерілген',
      years: 'жыл',
      book: 'Жазылу',
      notFound: 'Дәрігерлер табылмады',
      downloadApp: 'Қосымшаны жүктеп алыңыз',
      appDescription: 'Жазылуларды басқарыңыз және еске салуларды алыңыз',
      downloadIn: 'Жүктеп алу',
      availableIn: 'Қол жетімді',
      sum: 'сум',
    },
    articles: {
      title: 'Пайдалы мақалалар',
      subtitle: 'Тіс денсаулығы туралы сарапшы материалдары',
      heroTitle: 'Стоматология туралы пайдалы мақалалар',
      heroSubtitle: 'Жетекші мамандардан тіс денсаулығы туралы сарапшы материалдары',
      readMore: 'Толығырақ оқу',
      featured: 'Ұсынылған',
      readTime: 'мин оқу',
      backToArticles: 'Мақалаларға',
      relatedArticles: 'Ұқсас мақалалар',
      noArticles: 'Мақалалар табылмады',
      categories: {
        all: 'Барлық мақалалар',
        prevention: 'Алдын алу',
        treatment: 'Емдеу',
        children: 'Балалар стоматологиясы',
        cosmetic: 'Косметикалық стоматология',
      },
    },
    auth: {
      login: 'Кіру',
      register: 'Тіркелу',
      loginTab: 'Кіру',
      registerTab: 'Тіркелу',
      email: 'Email',
      password: 'Құпия сөз',
      confirmPassword: 'Құпия сөзді растаңыз',
      fullName: 'Толық аты',
      phone: 'Телефон',
      forgotPassword: 'Құпия сөзді ұмыттыңыз ба?',
      noAccount: 'Тіркелгіңіз жоқ па?',
      hasAccount: 'Тіркелгіңіз бар ма?',
      accountType: 'Тіркелгі түрі',
      patient: 'Пациент',
      doctor: 'Дәрігер',
      clinic: 'Клиника',
      loginButton: 'Кіру',
      registerButton: 'Тіркелу',
      or: 'Немесе',
      googleLogin: 'Google арқылы кіру',
      termsText: 'Жалғастыра отырып, сіз біздің',
      termsLink: 'қолдану шарттарымызға',
      and: 'және',
      privacyLink: 'құпиялылық саясатымызға келісесіз',
      createAccount: 'Платформаға кіру үшін тіркелгі жасаңыз',
      loginToAccount: 'Тіркелгіңізге кіріңіз',
      doctorNote: 'Тіркелгеннен кейін әкімші тексеруі үшін құжаттармен өтініш толтыру қажет',
      passwordMismatch: 'Құпия сөздер сәйкес келмейді',
      passwordTooShort: 'Құпия сөз кемінде 6 таңбадан тұруы керек',
    },
    profile: {
      tabs: {
        timeline: 'Лента',
        portfolio: 'Портфолио',
        reviews: 'Пікірлер',
        about: 'Дәрігер туралы',
        services: 'Қызметтер',
        settings: 'Баптаулар',
      },
      follow: 'Жазылу',
      following: 'Жазылған',
      message: 'Жазу',
      book: 'Жазылу',
      followers: 'жазылушы',
      experience: 'жыл тәжірибе',
      patients: 'пациент',
      reviews: 'пікір',
      verified: 'Тексерілген',
      edit: 'Өңдеу',
      save: 'Сақтау',
      cancel: 'Болдырмау',
    },
    crm: {
      dashboard: 'Басқару панелі',
      patients: 'Пациенттер',
      appointments: 'Жазылулар',
      schedule: 'Кесте',
      finance: 'Қаржы',
      inventory: 'Қойма',
      laboratory: 'Зертхана',
      reports: 'Есептер',
      settings: 'Баптаулар',
      notifications: 'Хабарламалар',
      queue: 'Кезек',
      medicalRecords: 'Медициналық карталар',
      ads: 'Жарнама',
      profile: 'Профиль',
      doctorRequests: 'Дәрігерлер сұраулары',
      messages: 'Хабарламалар',
      services: 'Қызметтер',
      billing: 'Төлем және жазылымдар',
      lightTheme: 'Жарық тақырып',
      darkTheme: 'Қараңғы тақырып',
      logout: 'Шығу',
    },
    patient: {
      dashboard: 'Басты бет',
      appointments: 'Жазылулар',
      medical: 'Медициналық карта',
      payments: 'Төлемдер',
      doctors: 'Менің дәрігерлерім',
      messages: 'Хабарламалар',
      files: 'Файлдар',
      family: 'Отбасы',
      reminders: 'Еске салулар',
      history: 'Тарих',
      bookAppointment: 'Жазылу',
    },
    common: {
      loading: 'Жүктелуде...',
      error: 'Қате',
      success: 'Сәтті',
      save: 'Сақтау',
      cancel: 'Болдырмау',
      delete: 'Жою',
      edit: 'Өңдеу',
      add: 'Қосу',
      close: 'Жабу',
      confirm: 'Растау',
      back: 'Артқа',
      next: 'Келесі',
      submit: 'Жіберу',
      search: 'Іздеу',
      all: 'Барлығы',
      yes: 'Иә',
      no: 'Жоқ',
      or: 'немесе',
      from: 'бастап',
      to: 'дейін',
      today: 'Бүгін',
      yesterday: 'Кеше',
      tomorrow: 'Ертең',
      week: 'Апта',
      month: 'Ай',
      year: 'Жыл',
    },
  },
  kg: {
    nav: {
      home: 'Башкы бет',
      search: 'Дарыгер табуу',
      clinics: 'Клиникалар',
      promotions: 'Акциялар',
      articles: 'Макалалар',
      about: 'Долбоор жөнүндө',
      login: 'Кирүү',
      profile: 'Профиль',
      logout: 'Чыгуу',
    },
    hero: {
      badge: 'Борбордук Азиянын №1 Стоматология Платформасы',
      subtitle: 'Борбордук Азиянын Премиум Стоматология Порталы',
      description: '500+ текшерилген дарыгерлер, онлайн тез жазылуу, чыныгы пикирлер жана иш фотолору',
      selectSpecialty: 'Адистикти тандаңыз',
      selectCity: 'Шаарды тандаңыз',
      searchButton: 'Издөө',
      doctors: 'Дарыгерлер',
      rating: 'Рейтинг',
      appointments: 'Жазылуулар',
      quickLinks: {
        implants: 'Имплантация',
        braces: 'Брекеттер',
        whitening: 'Агартуу',
        veneers: 'Винирлер',
        caries: 'Кариести дарылоо',
      },
      specialties: {
        therapist: 'Терапевт',
        orthodontist: 'Ортодонт',
        surgeon: 'Хирург',
        orthopedist: 'Ортопед',
        periodontist: 'Пародонтолог',
        pediatric: 'Балдар стоматологу',
      },
      cities: {
        tashkent: 'Ташкент',
        samarkand: 'Самарканд',
        bukhara: 'Бухара',
        andijan: 'Андижан',
        namangan: 'Наманган',
      },
    },
    features: {
      badge: 'ЭМНЕ ҮЧҮН БИЗ',
      title: 'Артыкчылыктар',
      brandName: 'PRODENT',
      subtitle: 'Биз стоматолог издөөнү жөнөкөй, тез жана ишенимдүү кылабыз',
      booking: {
        title: '7 секундда жазылуу',
        description: 'Чалуусуз жана күтүүсүз тез онлайн жазылуу',
      },
      verified: {
        title: 'Текшерилген дарыгерлер',
        description: 'Тастыкталган сертификаттары бар бардык адистер',
      },
      reviews: {
        title: 'Чыныгы пикирлер',
        description: 'Текшерилген чыныгы бейтаптардан гана пикирлер',
      },
      video: {
        title: 'Иш видеолору',
        description: '"Алдында" жана "кийин" натыйжаларын видео форматында көрүңүз',
      },
      reminders: {
        title: 'Эскертүүлөр',
        description: 'Алдыдагы сапар жөнүндө SMS жана Push-билдирүүлөр',
      },
      premium: {
        title: 'Бир гана премиум',
        description: 'Борбордук Азиянын эң мыкты клиникалары жана адистери',
      },
    },
    doctors: {
      badge: 'ТОП АДИСТЕР',
      title: 'Эң мыкты дарыгерлер',
      viewAll: 'Бардык дарыгерлер',
      experience: 'жыл тажрыйба',
      from: 'баштап',
      book: 'Жазылуу',
      viewProfile: 'Профиль',
      verified: 'Текшерилген',
      sum: 'сум',
    },
    promotions: {
      title: 'Актуалдуу',
      titleHighlight: 'акциялар',
      subtitle: 'Ташкенттин эң мыкты клиникаларынан атайын сунуштар',
      book: 'Жазылуу',
      viewAll: 'Бардык акцияларды көрүү',
      validUntil: 'Чейин',
      noPromotions: 'Тандалган категорияда акция жок',
      categories: {
        all: 'Баары',
        hygiene: 'Гигиена',
        orthodontics: 'Ортодонтия',
        aesthetics: 'Эстетика',
        implants: 'Имплантация',
        treatment: 'Дарылоо',
        pediatric: 'Балдар',
        surgery: 'Хирургия',
        periodontics: 'Пародонтология',
        prosthetics: 'Протездөө',
      },
    },
    clinics: {
      title: 'Стоматологиялык клиникалар',
      subtitle: 'Жакын жердеги эң жакшы клиниканы табыңыз',
      searchPlaceholder: 'Клиника аты боюнча издөө...',
      filters: 'Фильтрлер',
      searchFilters: 'Издөө фильтрлери',
      activeFilters: 'Активдүү фильтрлер:',
      search: 'Издөө',
      city: 'Шаар',
      allCities: 'Бардык шаарлар',
      district: 'Район',
      allDistricts: 'Бардык райондор',
      verifiedOnly: 'Текшерилгендер гана',
      resetFilters: 'Фильтрлерди тазалоо',
      resetAll: 'Баарын тазалоо',
      verified: 'Текшерилген',
      doctors: 'дарыгер',
      clinicFound: 'клиника табылды',
      clinicsFound2to4: 'клиника табылды',
      clinicsFound5plus: 'клиника табылды',
      notFound: 'Клиникалар табылган жок',
      notFoundHint: 'Издөө параметрлерин өзгөртүп көрүңүз',
      website: 'Сайт',
      email: 'Почта',
    },
    clinicProfile: {
      doctors: 'Дарыгерлер',
      about: 'Клиника жөнүндө',
    },
    footer: {
      description: 'Борбордук Азиянын биринчи премиум стоматология порталы',
      patients: 'Бейтаптарга',
      findDoctor: 'Дарыгер табуу',
      clinics: 'Клиникалар',
      promotions: 'Акциялар',
      reviews: 'Пикирлер',
      services: 'Кызматтар',
      implants: 'Имплантация',
      braces: 'Брекеттер',
      whitening: 'Агартуу',
      veneers: 'Винирлер',
      contacts: 'Байланыштар',
      address: 'Ташкент, Амир Темур көч., 129',
      rights: 'Бардык укуктар корголгон',
      privacy: 'Купуялык саясаты',
      terms: 'Колдонуу шарттары',
    },
    search: {
      title: 'Дарыгер издөө',
      placeholder: 'Дарыгер же клиника боюнча издөө...',
      onMap: 'Картада',
      filters: 'Фильтрлер',
      specialty: 'Адистик',
      allSpecialties: 'Бардык адистиктер',
      city: 'Шаар',
      district: 'Район',
      allDistricts: 'Бардык райондор',
      price: 'Баа',
      rating: 'Рейтинг',
      andAbove: 'жана жогору',
      withVideo: 'Иш видеолору менен гана',
      resetFilters: 'Фильтрлерди тазалоо',
      found: 'Табылды',
      doctorsCount: 'дарыгер',
      sort: 'Иреттөө',
      byRating: 'Рейтинг боюнча',
      byPriceAsc: 'Баа боюнча (өсүү)',
      byPriceDesc: 'Баа боюнча (төмөндөө)',
      byExperience: 'Тажрыйба боюнча',
      verified: 'Текшерилген',
      years: 'жыл',
      book: 'Жазылуу',
      notFound: 'Дарыгерлер табылган жок',
      downloadApp: 'Тиркемени жүктөп алыңыз',
      appDescription: 'Жазылууларды башкарыңыз жана эскертүүлөрдү алыңыз',
      downloadIn: 'Жүктөп алуу',
      availableIn: 'Жеткиликтүү',
      sum: 'сум',
    },
    articles: {
      title: 'Пайдалуу макалалар',
      subtitle: 'Тиш ден соолугу боюнча эксперт материалдары',
      heroTitle: 'Стоматология жөнүндө пайдалуу макалалар',
      heroSubtitle: 'Алдыңкы адистерден тиш ден соолугу боюнча эксперт материалдары',
      readMore: 'Толук окуу',
      featured: 'Сунушталган',
      readTime: 'мүн окуу',
      backToArticles: 'Макалаларга',
      relatedArticles: 'Окшош макалалар',
      noArticles: 'Макалалар табылган жок',
      categories: {
        all: 'Бардык макалалар',
        prevention: 'Алдын алуу',
        treatment: 'Дарылоо',
        children: 'Балдар стоматологиясы',
        cosmetic: 'Косметикалык стоматология',
      },
    },
    auth: {
      login: 'Кирүү',
      register: 'Катталуу',
      loginTab: 'Кирүү',
      registerTab: 'Катталуу',
      email: 'Email',
      password: 'Сыр сөз',
      confirmPassword: 'Сыр сөздү ырастаңыз',
      fullName: 'Толук аты',
      phone: 'Телефон',
      forgotPassword: 'Сыр сөздү унуттуңузбу?',
      noAccount: 'Аккаунтуңуз жокпу?',
      hasAccount: 'Аккаунтуңуз барбы?',
      accountType: 'Аккаунт түрү',
      patient: 'Бейтап',
      doctor: 'Дарыгер',
      clinic: 'Клиника',
      loginButton: 'Кирүү',
      registerButton: 'Катталуу',
      or: 'Же',
      googleLogin: 'Google аркылуу кирүү',
      termsText: 'Улантуу менен сиз биздин',
      termsLink: 'колдонуу шарттарыбызга',
      and: 'жана',
      privacyLink: 'купуялык саясатыбызга макулдугуңузду билдиресиз',
      createAccount: 'Платформага кирүү үчүн аккаунт түзүңүз',
      loginToAccount: 'Аккаунтуңузга кириңиз',
      doctorNote: 'Катталгандан кийин администратор текшерүүсү үчүн документтер менен арыз толтуруу керек',
      passwordMismatch: 'Сыр сөздөр дал келбейт',
      passwordTooShort: 'Сыр сөз кеминде 6 белгиден турушу керек',
    },
    profile: {
      tabs: {
        timeline: 'Лента',
        portfolio: 'Портфолио',
        reviews: 'Пикирлер',
        about: 'Дарыгер жөнүндө',
        services: 'Кызматтар',
        settings: 'Жөндөөлөр',
      },
      follow: 'Жазылуу',
      following: 'Жазылган',
      message: 'Жазуу',
      book: 'Жазылуу',
      followers: 'жазылуучу',
      experience: 'жыл тажрыйба',
      patients: 'бейтап',
      reviews: 'пикир',
      verified: 'Текшерилген',
      edit: 'Түзөтүү',
      save: 'Сактоо',
      cancel: 'Жокко чыгаруу',
    },
    crm: {
      dashboard: 'Башкаруу панели',
      patients: 'Бейтаптар',
      appointments: 'Жазылуулар',
      schedule: 'Расписание',
      finance: 'Каржы',
      inventory: 'Кампа',
      laboratory: 'Лаборатория',
      reports: 'Отчеттор',
      settings: 'Жөндөөлөр',
      notifications: 'Билдирүүлөр',
      queue: 'Кезек',
      medicalRecords: 'Медициналык карталар',
      ads: 'Жарнама',
      profile: 'Профиль',
      doctorRequests: 'Дарыгерлердин суроолору',
      messages: 'Кабарлар',
      services: 'Кызматтар',
      billing: 'Төлөм жана жазылуу',
      lightTheme: 'Жарык тема',
      darkTheme: 'Караңгы тема',
      logout: 'Чыгуу',
    },
    patient: {
      dashboard: 'Башкы бет',
      appointments: 'Жазылуулар',
      medical: 'Медициналык карта',
      payments: 'Төлөмдөр',
      doctors: 'Менин дарыгерлерим',
      messages: 'Кабарлар',
      files: 'Файлдар',
      family: 'Үй-бүлө',
      reminders: 'Эскертүүлөр',
      history: 'Тарых',
      bookAppointment: 'Жазылуу',
    },
    common: {
      loading: 'Жүктөлүүдө...',
      error: 'Ката',
      success: 'Ийгиликтүү',
      save: 'Сактоо',
      cancel: 'Жокко чыгаруу',
      delete: 'Өчүрүү',
      edit: 'Түзөтүү',
      add: 'Кошуу',
      close: 'Жабуу',
      confirm: 'Ырастоо',
      back: 'Артка',
      next: 'Кийинки',
      submit: 'Жөнөтүү',
      search: 'Издөө',
      all: 'Баары',
      yes: 'Ооба',
      no: 'Жок',
      or: 'же',
      from: 'баштап',
      to: 'чейин',
      today: 'Бүгүн',
      yesterday: 'Кечээ',
      tomorrow: 'Эртең',
      week: 'Жума',
      month: 'Ай',
      year: 'Жыл',
    },
  },
};
