import type { Language } from "@/contexts/LanguageContext";

export interface Dental3DCopy {
  noData: string;
  closeToothCard: string;
  fallbackFdiHint: string;
  accessDeniedTitle: string;
  loadFailedTitle: string;
  accessDeniedBody: string;
  loadFailedBody: string;
  retryLoad: string;
  ageUnknown: string;
  withoutData: string;
  formulaType: string;
  permanent: string;
  primary: string;
  bothJaws: string;
  resetModelAria: string;
  resetPosition: string;
  fullscreenModelAria: string;
  fullscreen: string;
  scopeNotice: string;
  controlsHint: string;
  webglUnavailable: string;
  modelOpenFailed: string;
  selectTooth: string;
  selectToothBody: string;
  historyUnavailableTitle: string;
  historyUnavailableBody: string;
  loading: string;
  retry: string;
  nextPageFailed: string;
  refreshHistoryFailed: string;
  showMore: string;
}

export const DENTAL_3D_COPY: Record<Language, Dental3DCopy> = {
  ru: {
    noData: "Нет данных",
    closeToothCard: "Закрыть карточку зуба",
    fallbackFdiHint: "Выберите FDI‑номер ниже — состояние и история лечения всё равно откроются.",
    accessDeniedTitle: "Нет доступа к зубной формуле",
    loadFailedTitle: "Зубная формула не загрузилась",
    accessDeniedBody: "Карту видит сам пациент, его врач или сотрудник клиники, которая ведёт лечение.",
    loadFailedBody: "Мы не показываем пустую схему как «здоровые зубы», чтобы не ввести врача и пациента в заблуждение.",
    retryLoad: "Повторить загрузку",
    ageUnknown: "Возраст не указан",
    withoutData: "без данных",
    formulaType: "Тип зубной формулы",
    permanent: "Постоянные",
    primary: "Молочные",
    bothJaws: "Обе челюсти",
    resetModelAria: "Сбросить положение 3D-модели",
    resetPosition: "Сбросить положение",
    fullscreenModelAria: "Открыть 3D-модель на весь экран",
    fullscreen: "На весь экран",
    scopeNotice: "Показаны только записи, доступные вам или вашей клинике. «Нет данных» не означает, что зуб никогда не лечили в другом месте.",
    controlsHint: "Вращайте · приближайте · нажмите на зуб",
    webglUnavailable: "3D недоступно на этом устройстве",
    modelOpenFailed: "3D-модель не смогла открыться",
    selectTooth: "Выберите зуб",
    selectToothBody: "Откроются его текущее состояние и история лечения.",
    historyUnavailableTitle: "История временно недоступна",
    historyUnavailableBody: "Не удалось загрузить записи. Повторите попытку.",
    loading: "Загрузка…",
    retry: "Повторить",
    nextPageFailed: "Не удалось загрузить следующие записи.",
    refreshHistoryFailed: "Не удалось обновить историю.",
    showMore: "Показать ещё",
  },
  uz: {
    noData: "Maʼlumot yoʻq",
    closeToothCard: "Tish kartasini yopish",
    fallbackFdiHint: "Quyidagi FDI raqamini tanlang — holat va davolash tarixi baribir ochiladi.",
    accessDeniedTitle: "Tish formulasini ko‘rishga ruxsat yo‘q",
    loadFailedTitle: "Tish formulasi yuklanmadi",
    accessDeniedBody: "Kartani faqat bemorning o‘zi, uning shifokori yoki davolayotgan klinika xodimi ko‘ra oladi.",
    loadFailedBody: "Shifokor va bemorni chalg‘itmaslik uchun bo‘sh sxemani «sog‘lom tishlar» deb ko‘rsatmaymiz.",
    retryLoad: "Qayta yuklash",
    ageUnknown: "Yosh ko‘rsatilmagan",
    withoutData: "maʼlumotsiz",
    formulaType: "Tish formulasi turi",
    permanent: "Doimiy",
    primary: "Sut tishlari",
    bothJaws: "Ikkala jag‘",
    resetModelAria: "3D model holatini tiklash",
    resetPosition: "Holatni tiklash",
    fullscreenModelAria: "3D modelni to‘liq ekranda ochish",
    fullscreen: "To‘liq ekran",
    scopeNotice: "Faqat sizga yoki klinikangizga ochiq yozuvlar ko‘rsatilgan. «Maʼlumot yoʻq» tish boshqa joyda hech qachon davolanmaganini anglatmaydi.",
    controlsHint: "Aylantiring · yaqinlashtiring · tishni bosing",
    webglUnavailable: "Bu qurilmada 3D ishlamaydi",
    modelOpenFailed: "3D model ochilmadi",
    selectTooth: "Tishni tanlang",
    selectToothBody: "Uning joriy holati va davolash tarixi ochiladi.",
    historyUnavailableTitle: "Tarix vaqtincha mavjud emas",
    historyUnavailableBody: "Yozuvlarni yuklab bo‘lmadi. Qayta urinib ko‘ring.",
    loading: "Yuklanmoqda…",
    retry: "Qayta urinish",
    nextPageFailed: "Keyingi yozuvlarni yuklab bo‘lmadi.",
    refreshHistoryFailed: "Tarixni yangilab bo‘lmadi.",
    showMore: "Yana ko‘rsatish",
  },
  uz_cyrl: {
    noData: "Маълумот йўқ",
    closeToothCard: "Тиш картасини ёпиш",
    fallbackFdiHint: "Қуйидаги FDI рақамини танланг — ҳолат ва даволаш тарихи барибир очилади.",
    accessDeniedTitle: "Тиш формуласини кўришга рухсат йўқ",
    loadFailedTitle: "Тиш формуласи юкланмади",
    accessDeniedBody: "Картани фақат беморнинг ўзи, унинг шифокори ёки даволаётган клиника ходими кўра олади.",
    loadFailedBody: "Шифокор ва беморни чалғитмаслик учун бўш схемани «соғлом тишлар» деб кўрсатмаймиз.",
    retryLoad: "Қайта юклаш",
    ageUnknown: "Ёш кўрсатилмаган",
    withoutData: "маълумотсиз",
    formulaType: "Тиш формуласи тури",
    permanent: "Доимий",
    primary: "Сут тишлари",
    bothJaws: "Иккала жағ",
    resetModelAria: "3D модель ҳолатини тиклаш",
    resetPosition: "Ҳолатни тиклаш",
    fullscreenModelAria: "3D моделни тўлиқ экранда очиш",
    fullscreen: "Тўлиқ экран",
    scopeNotice: "Фақат сизга ёки клиникангизга очиқ ёзувлар кўрсатилган. «Маълумот йўқ» тиш бошқа жойда ҳеч қачон даволанмаганини англатмайди.",
    controlsHint: "Айлантиринг · яқинлаштиринг · тишни босинг",
    webglUnavailable: "Бу қурилмада 3D ишламайди",
    modelOpenFailed: "3D модель очилмади",
    selectTooth: "Тишни танланг",
    selectToothBody: "Унинг жорий ҳолати ва даволаш тарихи очилади.",
    historyUnavailableTitle: "Тарих вақтинча мавжуд эмас",
    historyUnavailableBody: "Ёзувларни юклаб бўлмади. Қайта уриниб кўринг.",
    loading: "Юкланмоқда…",
    retry: "Қайта уриниш",
    nextPageFailed: "Кейинги ёзувларни юклаб бўлмади.",
    refreshHistoryFailed: "Тарихни янгилаб бўлмади.",
    showMore: "Яна кўрсатиш",
  },
  kz: {
    noData: "Дерек жоқ",
    closeToothCard: "Тіс картасын жабу",
    fallbackFdiHint: "Төмендегі FDI нөмірін таңдаңыз — тістің күйі мен емдеу тарихы бәрібір ашылады.",
    accessDeniedTitle: "Тіс формуласына кіруге рұқсат жоқ",
    loadFailedTitle: "Тіс формуласы жүктелмеді",
    accessDeniedBody: "Картаны тек пациенттің өзі, оның дәрігері немесе ем жүргізіп жатқан клиника қызметкері көре алады.",
    loadFailedBody: "Дәрігер мен пациентті шатастырмау үшін бос сызбаны «сау тістер» деп көрсетпейміз.",
    retryLoad: "Қайта жүктеу",
    ageUnknown: "Жасы көрсетілмеген",
    withoutData: "дерексіз",
    formulaType: "Тіс формуласының түрі",
    permanent: "Тұрақты",
    primary: "Сүт тістері",
    bothJaws: "Екі жақ сүйек",
    resetModelAria: "3D модель қалпын бастапқы күйге қайтару",
    resetPosition: "Қалпын бастапқы күйге қайтару",
    fullscreenModelAria: "3D модельді толық экранда ашу",
    fullscreen: "Толық экран",
    scopeNotice: "Тек сізге немесе клиникаңызға қолжетімді жазбалар көрсетілді. «Дерек жоқ» деген тіс басқа жерде ешқашан емделмеген дегенді білдірмейді.",
    controlsHint: "Айналдырыңыз · жақындатыңыз · тісті басыңыз",
    webglUnavailable: "Бұл құрылғыда 3D қолжетімсіз",
    modelOpenFailed: "3D модель ашылмады",
    selectTooth: "Тісті таңдаңыз",
    selectToothBody: "Оның қазіргі күйі мен емдеу тарихы ашылады.",
    historyUnavailableTitle: "Тарих уақытша қолжетімсіз",
    historyUnavailableBody: "Жазбаларды жүктеу мүмкін болмады. Қайталап көріңіз.",
    loading: "Жүктелуде…",
    retry: "Қайталау",
    nextPageFailed: "Келесі жазбаларды жүктеу мүмкін болмады.",
    refreshHistoryFailed: "Тарихты жаңарту мүмкін болмады.",
    showMore: "Тағы көрсету",
  },
  kg: {
    noData: "Маалымат жок",
    closeToothCard: "Тиш картасын жабуу",
    fallbackFdiHint: "Төмөнкү FDI номерин тандаңыз — тиштин абалы жана дарылоо тарыхы баары бир ачылат.",
    accessDeniedTitle: "Тиш формуласына кирүүгө уруксат жок",
    loadFailedTitle: "Тиш формуласы жүктөлгөн жок",
    accessDeniedBody: "Картаны бейтап өзү, анын дарыгери же дарылоону жүргүзгөн клиниканын кызматкери гана көрө алат.",
    loadFailedBody: "Дарыгер менен бейтапты адаштырбоо үчүн бош схеманы «соо тиштер» деп көрсөтпөйбүз.",
    retryLoad: "Кайра жүктөө",
    ageUnknown: "Жашы көрсөтүлгөн эмес",
    withoutData: "маалыматсыз",
    formulaType: "Тиш формуласынын түрү",
    permanent: "Туруктуу",
    primary: "Сүт тиштери",
    bothJaws: "Эки жаак",
    resetModelAria: "3D моделдин абалын баштапкыга кайтаруу",
    resetPosition: "Абалды баштапкыга кайтаруу",
    fullscreenModelAria: "3D моделди толук экранда ачуу",
    fullscreen: "Толук экран",
    scopeNotice: "Сизге же клиникаңызга жеткиликтүү жазуулар гана көрсөтүлдү. «Маалымат жок» тиш башка жерде эч качан дарыланган эмес дегенди билдирбейт.",
    controlsHint: "Айландырыңыз · жакындатыңыз · тишти басыңыз",
    webglUnavailable: "Бул түзмөктө 3D жеткиликсиз",
    modelOpenFailed: "3D модель ачылган жок",
    selectTooth: "Тишти тандаңыз",
    selectToothBody: "Анын учурдагы абалы жана дарылоо тарыхы ачылат.",
    historyUnavailableTitle: "Тарых убактылуу жеткиликсиз",
    historyUnavailableBody: "Жазууларды жүктөө мүмкүн болгон жок. Кайра аракет кылыңыз.",
    loading: "Жүктөлүүдө…",
    retry: "Кайра аракет кылуу",
    nextPageFailed: "Кийинки жазууларды жүктөө мүмкүн болгон жок.",
    refreshHistoryFailed: "Тарыхты жаңыртуу мүмкүн болгон жок.",
    showMore: "Дагы көрсөтүү",
  },
  tj: {
    noData: "Маълумот нест",
    closeToothCard: "Пӯшидани корти дандон",
    fallbackFdiHint: "Рақами FDI-ро дар поён интихоб кунед — ҳолат ва таърихи табобат ба ҳар ҳол кушода мешаванд.",
    accessDeniedTitle: "Дастрасӣ ба формулаи дандонҳо нест",
    loadFailedTitle: "Формулаи дандонҳо бор нашуд",
    accessDeniedBody: "Кортро танҳо худи бемор, духтури ӯ ё корманди клиникае, ки табобат мекунад, дида метавонад.",
    loadFailedBody: "Барои гумроҳ накардани духтур ва бемор, нақшаи холиро ҳамчун «дандонҳои солим» нишон намедиҳем.",
    retryLoad: "Аз нав бор кардан",
    ageUnknown: "Синну сол нишон дода нашудааст",
    withoutData: "бе маълумот",
    formulaType: "Навъи формулаи дандонҳо",
    permanent: "Доимӣ",
    primary: "Ширӣ",
    bothJaws: "Ҳар ду ҷоғ",
    resetModelAria: "Барқарор кардани мавқеи модели 3D",
    resetPosition: "Барқарор кардани мавқеъ",
    fullscreenModelAria: "Кушодани модели 3D дар тамоми экран",
    fullscreen: "Тамоми экран",
    scopeNotice: "Танҳо сабтҳое нишон дода шудаанд, ки ба шумо ё клиникаатон дастрасанд. «Маълумот нест» маънои онро надорад, ки дандон ҳеҷ гоҳ дар ҷои дигар табобат нашудааст.",
    controlsHint: "Чархонед · наздик кунед · дандонро пахш кунед",
    webglUnavailable: "3D дар ин дастгоҳ дастрас нест",
    modelOpenFailed: "Модели 3D кушода нашуд",
    selectTooth: "Дандонро интихоб кунед",
    selectToothBody: "Ҳолати ҷорӣ ва таърихи табобати он кушода мешаванд.",
    historyUnavailableTitle: "Таърих муваққатан дастнорас аст",
    historyUnavailableBody: "Сабтҳоро бор карда натавонистем. Аз нав кӯшиш кунед.",
    loading: "Бор шуда истодааст…",
    retry: "Аз нав кӯшиш кардан",
    nextPageFailed: "Сабтҳои навбатиро бор карда натавонистем.",
    refreshHistoryFailed: "Таърихро нав карда натавонистем.",
    showMore: "Боз нишон додан",
  },
};
