-- Fix all demo accounts to use a single working password: Demo2026Pass!
-- Removes duplicates and consolidates 9 accounts (one per role).
--
-- BCrypt hash below was generated by Spring at registration time and verified
-- against the password "Demo2026Pass!" via the /api/v1/auth/login endpoint.

-- 1. Repair the 3 broken seed accounts (admin@/doctor@/patient@) ──────────
UPDATE users
   SET password_hash = '$2a$10$7vF7IS61fQXcw3wCrRn7GeIX9hSqGv9xzuq2Z9m22SAz1Jy.k4YIC'
 WHERE email IN ('admin@prodent.uz', 'doctor@prodent.uz', 'patient@prodent.uz');

-- 2. Drop the duplicate accounts created via /register ─────────────────────
-- (they are functional copies of admin@/doctor@/patient@)
DELETE FROM user_roles WHERE user_id IN (
  SELECT id FROM users WHERE email IN ('superadmin@prodent.uz', 'doc@prodent.uz', 'pat@prodent.uz')
);
DELETE FROM users WHERE email IN ('superadmin@prodent.uz', 'doc@prodent.uz', 'pat@prodent.uz');

-- 3. Verify final state ────────────────────────────────────────────────────
SELECT u.email, ur.role
  FROM users u
  JOIN user_roles ur ON ur.user_id = u.id
 ORDER BY ur.role, u.email;
